### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by boguz** [Ceheiss/LordOfTheIpsum#1]
I have just tried to to create some lorem on your page but i couldn't get it to work.
When i click on the "For gondor" button nothing happens.

I noticed there is a warning and an error on the console, but it is just the favicon missing
![image](https://user-images.githubusercontent.com/15846102/85272033-e984e800-b47b-11ea-83d8-e89c4dc4711b.png)

I think there might be a problem with how you are fetching the data.
Are you getting the correct data back?

I hope you get it to work, i really like the idea of a LOTR lorem generator!   ;)

**Comment by Ceheiss** [comment]
Hey @boguz I'm actually thrilled someone at least tried to use this small app :) I just saw this issue and yes, the site where I was hosting the JSON file apparently disappeared so I just built a new one and saved it as a gist. Thanks again for leaving a message.
